# Generated by Django 5.1.6 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_delete_healthrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profile",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="notification_preference",
            field=models.CharField(
                choices=[("email", "Email"), ("app", "App")],
                default="app",
                max_length=10,
            ),
        ),
    ]
