# Generated by Django 4.2.19 on 2025-02-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('requirement', models.TextField(verbose_name='获取条件')),
                ('points', models.IntegerField(verbose_name='积分值')),
                ('badge_image', models.ImageField(upload_to='badges/', verbose_name='徽章图片')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='难度等级')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateTimeField(auto_now_add=True, verbose_name='获得日期')),
                ('progress', models.IntegerField(default=0, verbose_name='当前进度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='奖励是否已领取')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
