# Generated by Django 5.1.6 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.AlterModelOptions(
            name="userachievement",
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
            },
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="reward_claimed",
        ),
        migrations.AlterField(
            model_name="achievement",
            name="badge_image",
            field=models.ImageField(upload_to="badges/", verbose_name="badge image"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="category",
            field=models.CharField(max_length=50, verbose_name="category"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=100, verbose_name="achievement name"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="points",
            field=models.IntegerField(verbose_name="points"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="requirement",
            field=models.TextField(verbose_name="requirement"),
        ),
        migrations.AlterField(
            model_name="userachievement",
            name="achieved_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="achieved_date"),
        ),
    ]
