# Generated by Django 4.2.19 on 2025-02-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('species', models.CharField(choices=[('dog', '狗'), ('cat', '猫'), ('rabbit', '兔子'), ('hamster', '仓鼠'), ('other', '其他')], max_length=20, verbose_name='物种')),
                ('breed', models.CharField(max_length=50, verbose_name='品种')),
                ('birthdate', models.DateField(verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('M', '公'), ('F', '母'), ('U', '未知')], max_length=1, verbose_name='性别')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重(kg)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='照片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'ordering': ['-created_at'],
            },
        ),
    ]
