# Generated by Django 5.1.6 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "pet",
                "verbose_name_plural": "pet",
            },
        ),
        migrations.AlterField(
            model_name="pet",
            name="birthdate",
            field=models.DateField(verbose_name="Birthdate"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=models.CharField(max_length=50, verbose_name="Breed"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="reated_at"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="pets/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[
                    ("dog", "Dog"),
                    ("cat", "Cat"),
                    ("rabbit", "Rabbit"),
                    ("hamster", "Hamster"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="Species",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated_at"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Weight(kg)"
            ),
        ),
    ]
