# Generated by Django 4.2.19 on 2025-02-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccine', '疫苗'), ('checkup', '体检'), ('treatment', '治疗'), ('routine', '日常检查')], max_length=20, verbose_name='记录类型')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('status', models.CharField(choices=[('healthy', '健康'), ('sick', '生病'), ('recovering', '恢复中'), ('critical', '危重')], max_length=20, verbose_name='健康状态')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重(kg)')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='体温(℃)')),
                ('symptoms', models.TextField(blank=True, verbose_name='症状')),
                ('diagnosis', models.TextField(blank=True, verbose_name='诊断')),
                ('treatment', models.TextField(blank=True, verbose_name='治疗方案')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='下次就诊日期')),
                ('vet_name', models.CharField(max_length=100, verbose_name='兽医姓名')),
                ('clinic_name', models.CharField(max_length=200, verbose_name='诊所名称')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-record_date'],
            },
        ),
    ]
