# Generated by Django 5.1.6 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthrecord",
            options={
                "ordering": ["-record_date"],
                "verbose_name": "health record",
                "verbose_name_plural": "health record",
            },
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="clinic_name",
            field=models.CharField(max_length=200, verbose_name="clinic name"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="diagnosis",
            field=models.TextField(blank=True, verbose_name="diagnosis"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="next_visit_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="next visit date"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="record_date",
            field=models.DateField(verbose_name="record date"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("vaccine", "Vaccine"),
                    ("checkup", "Checkup"),
                    ("treatment", "Treatment"),
                    ("routine", "Routine"),
                ],
                max_length=20,
                verbose_name="record type",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("sick", "Sick"),
                    ("recovering", "Recovering"),
                    ("critical", "Critical"),
                ],
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="symptoms",
            field=models.TextField(blank=True, verbose_name="symptoms"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="temperature",
            field=models.DecimalField(
                decimal_places=1, max_digits=4, verbose_name="temperature(℃)"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="treatment",
            field=models.TextField(blank=True, verbose_name="treatment"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="vet_name",
            field=models.CharField(max_length=100, verbose_name="vet name"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="weight(kg)"
            ),
        ),
    ]
